language: go
go:
  - "1.12"
install:
  - export GO111MODULE=on
  - go mod download
  - go get github.com/golang/protobuf/protoc-gen-go
before_script:
  - cd testcli
  - go build
  - ./testcli init
  - chmod +x protocli.bats
script:
  - ./protocli.bats
