// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ValidateErrorType int32

const (
	ValidateErrorType_INVALID_EMAIL  ValidateErrorType = 0
	ValidateErrorType_FIELD_REQUIRED ValidateErrorType = 1
)

var ValidateErrorType_name = map[int32]string{
	0: "INVALID_EMAIL",
	1: "FIELD_REQUIRED",
}

var ValidateErrorType_value = map[string]int32{
	"INVALID_EMAIL":  0,
	"FIELD_REQUIRED": 1,
}

func (x ValidateErrorType) String() string {
	return proto.EnumName(ValidateErrorType_name, int32(x))
}

func (ValidateErrorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

type CommonError struct {
	GenericError         *GenericError  `protobuf:"bytes,1,opt,name=genericError,proto3" json:"genericError,omitempty"`
	AuthError            *AuthError     `protobuf:"bytes,2,opt,name=authError,proto3" json:"authError,omitempty"`
	ValidateError        *ValidateError `protobuf:"bytes,3,opt,name=validateError,proto3" json:"validateError,omitempty"`
	BindError            *BindError     `protobuf:"bytes,4,opt,name=bindError,proto3" json:"bindError,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CommonError) Reset()         { *m = CommonError{} }
func (m *CommonError) String() string { return proto.CompactTextString(m) }
func (*CommonError) ProtoMessage()    {}
func (*CommonError) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *CommonError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonError.Unmarshal(m, b)
}
func (m *CommonError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonError.Marshal(b, m, deterministic)
}
func (m *CommonError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonError.Merge(m, src)
}
func (m *CommonError) XXX_Size() int {
	return xxx_messageInfo_CommonError.Size(m)
}
func (m *CommonError) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonError.DiscardUnknown(m)
}

var xxx_messageInfo_CommonError proto.InternalMessageInfo

func (m *CommonError) GetGenericError() *GenericError {
	if m != nil {
		return m.GenericError
	}
	return nil
}

func (m *CommonError) GetAuthError() *AuthError {
	if m != nil {
		return m.AuthError
	}
	return nil
}

func (m *CommonError) GetValidateError() *ValidateError {
	if m != nil {
		return m.ValidateError
	}
	return nil
}

func (m *CommonError) GetBindError() *BindError {
	if m != nil {
		return m.BindError
	}
	return nil
}

type GenericError struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenericError) Reset()         { *m = GenericError{} }
func (m *GenericError) String() string { return proto.CompactTextString(m) }
func (*GenericError) ProtoMessage()    {}
func (*GenericError) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *GenericError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericError.Unmarshal(m, b)
}
func (m *GenericError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericError.Marshal(b, m, deterministic)
}
func (m *GenericError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericError.Merge(m, src)
}
func (m *GenericError) XXX_Size() int {
	return xxx_messageInfo_GenericError.Size(m)
}
func (m *GenericError) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericError.DiscardUnknown(m)
}

var xxx_messageInfo_GenericError proto.InternalMessageInfo

func (m *GenericError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AuthError struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthError) Reset()         { *m = AuthError{} }
func (m *AuthError) String() string { return proto.CompactTextString(m) }
func (*AuthError) ProtoMessage()    {}
func (*AuthError) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *AuthError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthError.Unmarshal(m, b)
}
func (m *AuthError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthError.Marshal(b, m, deterministic)
}
func (m *AuthError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthError.Merge(m, src)
}
func (m *AuthError) XXX_Size() int {
	return xxx_messageInfo_AuthError.Size(m)
}
func (m *AuthError) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthError.DiscardUnknown(m)
}

var xxx_messageInfo_AuthError proto.InternalMessageInfo

func (m *AuthError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type BindError struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BindError) Reset()         { *m = BindError{} }
func (m *BindError) String() string { return proto.CompactTextString(m) }
func (*BindError) ProtoMessage()    {}
func (*BindError) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}

func (m *BindError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindError.Unmarshal(m, b)
}
func (m *BindError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindError.Marshal(b, m, deterministic)
}
func (m *BindError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindError.Merge(m, src)
}
func (m *BindError) XXX_Size() int {
	return xxx_messageInfo_BindError.Size(m)
}
func (m *BindError) XXX_DiscardUnknown() {
	xxx_messageInfo_BindError.DiscardUnknown(m)
}

var xxx_messageInfo_BindError proto.InternalMessageInfo

func (m *BindError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ValidateError struct {
	Errors               []*FieldError `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ValidateError) Reset()         { *m = ValidateError{} }
func (m *ValidateError) String() string { return proto.CompactTextString(m) }
func (*ValidateError) ProtoMessage()    {}
func (*ValidateError) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{4}
}

func (m *ValidateError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateError.Unmarshal(m, b)
}
func (m *ValidateError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateError.Marshal(b, m, deterministic)
}
func (m *ValidateError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateError.Merge(m, src)
}
func (m *ValidateError) XXX_Size() int {
	return xxx_messageInfo_ValidateError.Size(m)
}
func (m *ValidateError) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateError.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateError proto.InternalMessageInfo

func (m *ValidateError) GetErrors() []*FieldError {
	if m != nil {
		return m.Errors
	}
	return nil
}

type FieldError struct {
	FieldName            string            `protobuf:"bytes,1,opt,name=fieldName,proto3" json:"fieldName,omitempty"`
	ErrorType            ValidateErrorType `protobuf:"varint,2,opt,name=errorType,proto3,enum=common.ValidateErrorType" json:"errorType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FieldError) Reset()         { *m = FieldError{} }
func (m *FieldError) String() string { return proto.CompactTextString(m) }
func (*FieldError) ProtoMessage()    {}
func (*FieldError) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{5}
}

func (m *FieldError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldError.Unmarshal(m, b)
}
func (m *FieldError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldError.Marshal(b, m, deterministic)
}
func (m *FieldError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldError.Merge(m, src)
}
func (m *FieldError) XXX_Size() int {
	return xxx_messageInfo_FieldError.Size(m)
}
func (m *FieldError) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldError.DiscardUnknown(m)
}

var xxx_messageInfo_FieldError proto.InternalMessageInfo

func (m *FieldError) GetFieldName() string {
	if m != nil {
		return m.FieldName
	}
	return ""
}

func (m *FieldError) GetErrorType() ValidateErrorType {
	if m != nil {
		return m.ErrorType
	}
	return ValidateErrorType_INVALID_EMAIL
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{6}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

var E_ServiceMethod = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         51006,
	Name:          "common.service_method",
	Tag:           "bytes,51006,opt,name=service_method",
	Filename:      "common.proto",
}

var E_Error = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         51007,
	Name:          "common.error",
	Tag:           "bytes,51007,opt,name=error",
	Filename:      "common.proto",
}

var E_CommonError = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.ServiceOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         51008,
	Name:          "common.common_error",
	Tag:           "bytes,51008,opt,name=common_error",
	Filename:      "common.proto",
}

var E_Auth = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.ServiceOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         51009,
	Name:          "common.auth",
	Tag:           "varint,51009,opt,name=auth",
	Filename:      "common.proto",
}

var E_ValFormat = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         51002,
	Name:          "common.val_format",
	Tag:           "bytes,51002,opt,name=val_format",
	Filename:      "common.proto",
}

var E_ValRequired = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         51003,
	Name:          "common.val_required",
	Tag:           "varint,51003,opt,name=val_required",
	Filename:      "common.proto",
}

var E_Min = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*int32)(nil),
	Field:         51004,
	Name:          "common.min",
	Tag:           "varint,51004,opt,name=min",
	Filename:      "common.proto",
}

var E_Max = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*int32)(nil),
	Field:         51005,
	Name:          "common.max",
	Tag:           "varint,51005,opt,name=max",
	Filename:      "common.proto",
}

func init() {
	proto.RegisterEnum("common.ValidateErrorType", ValidateErrorType_name, ValidateErrorType_value)
	proto.RegisterType((*CommonError)(nil), "common.CommonError")
	proto.RegisterType((*GenericError)(nil), "common.GenericError")
	proto.RegisterType((*AuthError)(nil), "common.AuthError")
	proto.RegisterType((*BindError)(nil), "common.BindError")
	proto.RegisterType((*ValidateError)(nil), "common.ValidateError")
	proto.RegisterType((*FieldError)(nil), "common.FieldError")
	proto.RegisterType((*Empty)(nil), "common.Empty")
	proto.RegisterExtension(E_ServiceMethod)
	proto.RegisterExtension(E_Error)
	proto.RegisterExtension(E_CommonError)
	proto.RegisterExtension(E_Auth)
	proto.RegisterExtension(E_ValFormat)
	proto.RegisterExtension(E_ValRequired)
	proto.RegisterExtension(E_Min)
	proto.RegisterExtension(E_Max)
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 504 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xeb, 0x8a, 0xd3, 0x40,
	0x14, 0xc7, 0xad, 0xdd, 0xed, 0x9a, 0xd3, 0x0b, 0xdb, 0x41, 0xa1, 0x8a, 0x97, 0x12, 0x10, 0xca,
	0x7e, 0x48, 0xb1, 0xe2, 0x85, 0x2c, 0x08, 0x5d, 0x9b, 0x2e, 0x81, 0xee, 0x8a, 0xa3, 0xee, 0xd7,
	0x30, 0x4d, 0xa6, 0xdd, 0x40, 0x92, 0x89, 0x93, 0x34, 0xec, 0xbe, 0x84, 0x0f, 0xe4, 0xdd, 0x97,
	0xf1, 0x39, 0x24, 0x33, 0x99, 0xa6, 0xa5, 0xb2, 0xf9, 0xd6, 0x33, 0xe7, 0xf7, 0xcb, 0xff, 0x4c,
	0x7a, 0x02, 0x2d, 0x97, 0x85, 0x21, 0x8b, 0x8c, 0x98, 0xb3, 0x94, 0xa1, 0x86, 0xac, 0x1e, 0xf4,
	0x97, 0x8c, 0x2d, 0x03, 0x3a, 0x14, 0xa7, 0xf3, 0xd5, 0x62, 0xe8, 0xd1, 0xc4, 0xe5, 0x7e, 0x9c,
	0x32, 0x2e, 0x49, 0xfd, 0x6f, 0x0d, 0x9a, 0x6f, 0x05, 0x6c, 0x71, 0xce, 0x38, 0x7a, 0x0d, 0xad,
	0x25, 0x8d, 0x28, 0xf7, 0x5d, 0x51, 0xf7, 0x6a, 0xfd, 0xda, 0xa0, 0x39, 0xba, 0x6b, 0x14, 0x8f,
	0x3f, 0xdd, 0xe8, 0xe1, 0x2d, 0x12, 0x0d, 0x41, 0x23, 0xab, 0xf4, 0x52, 0x6a, 0xb7, 0x85, 0xd6,
	0x55, 0xda, 0x58, 0x35, 0x70, 0xc9, 0xa0, 0x63, 0x68, 0x67, 0x24, 0xf0, 0x3d, 0x92, 0x52, 0x29,
	0xd5, 0x85, 0x74, 0x4f, 0x49, 0x17, 0x9b, 0x4d, 0xbc, 0xcd, 0xe6, 0x69, 0x73, 0x3f, 0xf2, 0xa4,
	0xb8, 0xb7, 0x9d, 0x76, 0xa2, 0x1a, 0xb8, 0x64, 0xf4, 0x01, 0xb4, 0x36, 0x87, 0x47, 0x3d, 0x38,
	0x08, 0x69, 0x92, 0x90, 0x25, 0x15, 0x77, 0xd4, 0xb0, 0x2a, 0xf5, 0xa7, 0xa0, 0xad, 0xe7, 0xbd,
	0x19, 0x5b, 0x07, 0xdd, 0x80, 0x1d, 0x43, 0x7b, 0xeb, 0x22, 0xe8, 0x08, 0x1a, 0x34, 0xff, 0x91,
	0xf4, 0x6a, 0xfd, 0xfa, 0xa0, 0x39, 0x42, 0x6a, 0xec, 0xa9, 0x4f, 0x83, 0x62, 0xee, 0x82, 0xd0,
	0x5d, 0x80, 0xf2, 0x14, 0x3d, 0x04, 0x6d, 0x91, 0x57, 0xe7, 0x24, 0x54, 0x31, 0xe5, 0x01, 0x7a,
	0x05, 0x9a, 0xb0, 0x3e, 0x5e, 0xc7, 0x54, 0xbc, 0xff, 0xce, 0xe8, 0xfe, 0x7f, 0x5f, 0x65, 0x0e,
	0xe0, 0x92, 0xd5, 0x0f, 0x60, 0xdf, 0x0a, 0xe3, 0xf4, 0xfa, 0xc8, 0x84, 0xee, 0x0e, 0x88, 0xba,
	0xd0, 0xb6, 0xcf, 0x2f, 0xc6, 0x33, 0x7b, 0xe2, 0x58, 0x67, 0x63, 0x7b, 0x76, 0x78, 0x0b, 0x21,
	0xe8, 0x4c, 0x6d, 0x6b, 0x36, 0x71, 0xb0, 0xf5, 0xfe, 0x93, 0x8d, 0xad, 0xc9, 0x61, 0xcd, 0x3c,
	0x85, 0x4e, 0x42, 0x79, 0xe6, 0xbb, 0xd4, 0x09, 0x69, 0x7a, 0xc9, 0x3c, 0xf4, 0xd8, 0x90, 0xcb,
	0x67, 0xa8, 0xe5, 0x33, 0xce, 0x44, 0xe3, 0x5d, 0x9c, 0xfa, 0x2c, 0x4a, 0x7a, 0x3f, 0xbf, 0xd4,
	0xc5, 0x15, 0xda, 0x85, 0x27, 0xbb, 0xe6, 0x4b, 0xd8, 0x17, 0xa3, 0x55, 0xfa, 0xbf, 0x0a, 0x5f,
	0xe2, 0xe6, 0x44, 0x7d, 0x02, 0x8e, 0xd4, 0x9f, 0xec, 0xe8, 0x1f, 0x64, 0x8e, 0xf2, 0x7f, 0x17,
	0x7e, 0xd3, 0x2d, 0xd7, 0xdf, 0x7c, 0x01, 0x7b, 0xf9, 0x82, 0x56, 0xdb, 0x7f, 0x84, 0x7d, 0x07,
	0x0b, 0xdc, 0x7c, 0x03, 0x90, 0x91, 0xc0, 0x59, 0x30, 0x1e, 0x92, 0x14, 0x3d, 0xda, 0x91, 0xc5,
	0x9f, 0xa8, 0xd4, 0xaf, 0x45, 0xb0, 0x96, 0x91, 0x60, 0x2a, 0x0c, 0xf3, 0x04, 0x5a, 0xb9, 0xcf,
	0xe9, 0xe7, 0x95, 0xcf, 0xa9, 0x57, 0xf5, 0x84, 0x6f, 0x45, 0x78, 0x33, 0x23, 0x01, 0x2e, 0x1c,
	0xf3, 0x19, 0xd4, 0x43, 0x3f, 0xaa, 0x52, 0xbf, 0x0b, 0x75, 0x1f, 0xe7, 0xac, 0x50, 0xc8, 0x55,
	0x95, 0xf2, 0x63, 0xad, 0x90, 0xab, 0x79, 0x43, 0x30, 0xcf, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff,
	0xe8, 0x4b, 0x9c, 0xd6, 0x70, 0x04, 0x00, 0x00,
}
