// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gopackage_addReq.proto

package calcsvr

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddReq struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddReq) Reset()         { *m = AddReq{} }
func (m *AddReq) String() string { return proto.CompactTextString(m) }
func (*AddReq) ProtoMessage()    {}
func (*AddReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_b51c09baf4f18e39, []int{0}
}

func (m *AddReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddReq.Unmarshal(m, b)
}
func (m *AddReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddReq.Marshal(b, m, deterministic)
}
func (m *AddReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddReq.Merge(m, src)
}
func (m *AddReq) XXX_Size() int {
	return xxx_messageInfo_AddReq.Size(m)
}
func (m *AddReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddReq proto.InternalMessageInfo

func (m *AddReq) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *AddReq) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func init() {
	proto.RegisterType((*AddReq)(nil), "AddReq")
}

func init() { proto.RegisterFile("gopackage_addReq.proto", fileDescriptor_b51c09baf4f18e39) }

var fileDescriptor_b51c09baf4f18e39 = []byte{
	// 92 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4b, 0xcf, 0x2f, 0x48,
	0x4c, 0xce, 0x4e, 0x4c, 0x4f, 0x8d, 0x4f, 0x4c, 0x49, 0x09, 0x4a, 0x2d, 0xd4, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x57, 0x52, 0xe1, 0x62, 0x73, 0x04, 0xf3, 0x85, 0x78, 0xb8, 0x18, 0x2b, 0x24, 0x18,
	0x15, 0x18, 0x35, 0x58, 0x83, 0x18, 0x2b, 0x40, 0xbc, 0x4a, 0x09, 0x26, 0x08, 0xaf, 0xd2, 0x89,
	0x33, 0x8a, 0x3d, 0x39, 0x31, 0x27, 0xb9, 0xb8, 0xac, 0x28, 0x89, 0x0d, 0xac, 0xcf, 0x18, 0x10,
	0x00, 0x00, 0xff, 0xff, 0x90, 0x55, 0x76, 0xbf, 0x51, 0x00, 0x00, 0x00,
}
