// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nopackage_calc.proto

package calcsvrmain

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddResp struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResp) Reset()         { *m = AddResp{} }
func (m *AddResp) String() string { return proto.CompactTextString(m) }
func (*AddResp) ProtoMessage()    {}
func (*AddResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbb4287df7fa02b4, []int{0}
}

func (m *AddResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResp.Unmarshal(m, b)
}
func (m *AddResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResp.Marshal(b, m, deterministic)
}
func (m *AddResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResp.Merge(m, src)
}
func (m *AddResp) XXX_Size() int {
	return xxx_messageInfo_AddResp.Size(m)
}
func (m *AddResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddResp proto.InternalMessageInfo

func (m *AddResp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type AddError struct {
	Req                  *AddReq  `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddError) Reset()         { *m = AddError{} }
func (m *AddError) String() string { return proto.CompactTextString(m) }
func (*AddError) ProtoMessage()    {}
func (*AddError) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbb4287df7fa02b4, []int{1}
}

func (m *AddError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddError.Unmarshal(m, b)
}
func (m *AddError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddError.Marshal(b, m, deterministic)
}
func (m *AddError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddError.Merge(m, src)
}
func (m *AddError) XXX_Size() int {
	return xxx_messageInfo_AddError.Size(m)
}
func (m *AddError) XXX_DiscardUnknown() {
	xxx_messageInfo_AddError.DiscardUnknown(m)
}

var xxx_messageInfo_AddError proto.InternalMessageInfo

func (m *AddError) GetReq() *AddReq {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *AddError) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*AddResp)(nil), "calcmain.AddResp")
	proto.RegisterType((*AddError)(nil), "calcmain.AddError")
}

func init() { proto.RegisterFile("nopackage_calc.proto", fileDescriptor_dbb4287df7fa02b4) }

var fileDescriptor_dbb4287df7fa02b4 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc9, 0xcb, 0x2f, 0x48,
	0x4c, 0xce, 0x4e, 0x4c, 0x4f, 0x8d, 0x4f, 0x4e, 0xcc, 0x49, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x00, 0xb1, 0x73, 0x13, 0x33, 0xf3, 0xa4, 0x78, 0x92, 0xf3, 0x73, 0x73, 0xf3, 0xf3,
	0x20, 0xe2, 0x52, 0x62, 0x08, 0xd5, 0x89, 0x29, 0x29, 0x41, 0xa9, 0x85, 0x10, 0x71, 0x25, 0x45,
	0x2e, 0x76, 0x47, 0x10, 0xbf, 0xb8, 0x40, 0x48, 0x8c, 0x8b, 0xad, 0x28, 0xb5, 0xb8, 0x34, 0xa7,
	0x44, 0x82, 0x51, 0x81, 0x51, 0x83, 0x35, 0x08, 0xca, 0x53, 0xb2, 0xe6, 0xe2, 0x70, 0x4c, 0x49,
	0x71, 0x2d, 0x2a, 0xca, 0x2f, 0x12, 0x92, 0xe4, 0x62, 0x2e, 0x4a, 0x2d, 0x04, 0x2b, 0xe0, 0x36,
	0x62, 0xd7, 0x03, 0x6b, 0x2d, 0x0c, 0x02, 0x89, 0x09, 0x89, 0x70, 0xb1, 0xa6, 0x82, 0xd4, 0x48,
	0x30, 0x29, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x38, 0x46, 0x61, 0x5c, 0xdc, 0xce, 0x89, 0x39, 0xc9,
	0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0x42, 0xfa, 0x5c, 0xcc, 0x89, 0x29, 0x29, 0x42, 0x30,
	0x9d, 0x52, 0x82, 0x7a, 0x30, 0xf7, 0xea, 0x41, 0x9d, 0xa1, 0xc4, 0xf3, 0xeb, 0xb3, 0x04, 0xdc,
	0x42, 0x29, 0xb1, 0xa6, 0x2f, 0x12, 0x42, 0x50, 0x9f, 0x38, 0x83, 0x29, 0xb0, 0xb8, 0x13, 0x6f,
	0x14, 0x37, 0x48, 0x67, 0x71, 0x59, 0x11, 0x48, 0x73, 0x12, 0x1b, 0xd8, 0x37, 0xc6, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x10, 0xf1, 0x8a, 0x52, 0x15, 0x01, 0x00, 0x00,
}
