// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nopackage_calc_warn.proto

package calcsvrmain

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddReq struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddReq) Reset()         { *m = AddReq{} }
func (m *AddReq) String() string { return proto.CompactTextString(m) }
func (*AddReq) ProtoMessage()    {}
func (*AddReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_17e3448b3146f43d, []int{0}
}

func (m *AddReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddReq.Unmarshal(m, b)
}
func (m *AddReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddReq.Marshal(b, m, deterministic)
}
func (m *AddReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddReq.Merge(m, src)
}
func (m *AddReq) XXX_Size() int {
	return xxx_messageInfo_AddReq.Size(m)
}
func (m *AddReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddReq proto.InternalMessageInfo

func (m *AddReq) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *AddReq) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type AddResp struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResp) Reset()         { *m = AddResp{} }
func (m *AddResp) String() string { return proto.CompactTextString(m) }
func (*AddResp) ProtoMessage()    {}
func (*AddResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_17e3448b3146f43d, []int{1}
}

func (m *AddResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResp.Unmarshal(m, b)
}
func (m *AddResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResp.Marshal(b, m, deterministic)
}
func (m *AddResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResp.Merge(m, src)
}
func (m *AddResp) XXX_Size() int {
	return xxx_messageInfo_AddResp.Size(m)
}
func (m *AddResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddResp proto.InternalMessageInfo

func (m *AddResp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type AddError struct {
	Req                  *AddReq  `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddError) Reset()         { *m = AddError{} }
func (m *AddError) String() string { return proto.CompactTextString(m) }
func (*AddError) ProtoMessage()    {}
func (*AddError) Descriptor() ([]byte, []int) {
	return fileDescriptor_17e3448b3146f43d, []int{2}
}

func (m *AddError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddError.Unmarshal(m, b)
}
func (m *AddError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddError.Marshal(b, m, deterministic)
}
func (m *AddError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddError.Merge(m, src)
}
func (m *AddError) XXX_Size() int {
	return xxx_messageInfo_AddError.Size(m)
}
func (m *AddError) XXX_DiscardUnknown() {
	xxx_messageInfo_AddError.DiscardUnknown(m)
}

var xxx_messageInfo_AddError proto.InternalMessageInfo

func (m *AddError) GetReq() *AddReq {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *AddError) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*AddReq)(nil), "calcmain.AddReq")
	proto.RegisterType((*AddResp)(nil), "calcmain.AddResp")
	proto.RegisterType((*AddError)(nil), "calcmain.AddError")
}

func init() { proto.RegisterFile("nopackage_calc_warn.proto", fileDescriptor_17e3448b3146f43d) }

var fileDescriptor_17e3448b3146f43d = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcc, 0xcb, 0x2f, 0x48,
	0x4c, 0xce, 0x4e, 0x4c, 0x4f, 0x8d, 0x4f, 0x4e, 0xcc, 0x49, 0x8e, 0x2f, 0x4f, 0x2c, 0xca, 0xd3,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x09, 0xe4, 0x26, 0x66, 0xe6, 0x49, 0xf1, 0x24,
	0xe7, 0xe7, 0xe6, 0xe6, 0x43, 0xc5, 0xa5, 0xc4, 0x10, 0x5a, 0x12, 0x53, 0x52, 0x82, 0x52, 0x0b,
	0x21, 0xe2, 0x4a, 0x2a, 0x5c, 0x6c, 0x8e, 0x60, 0xbe, 0x10, 0x0f, 0x17, 0x63, 0x85, 0x04, 0xa3,
	0x02, 0xa3, 0x06, 0x6b, 0x10, 0x63, 0x05, 0x88, 0x57, 0x29, 0xc1, 0x04, 0xe1, 0x55, 0x2a, 0x29,
	0x72, 0xb1, 0x83, 0x55, 0x15, 0x17, 0x08, 0x89, 0x71, 0xb1, 0x15, 0xa5, 0x16, 0x97, 0xe6, 0x94,
	0x40, 0xd5, 0x42, 0x79, 0x4a, 0x2e, 0x5c, 0x1c, 0x8e, 0x29, 0x29, 0xae, 0x45, 0x45, 0xf9, 0x45,
	0x42, 0x4a, 0x5c, 0xcc, 0x45, 0xa9, 0x85, 0x60, 0x05, 0xdc, 0x46, 0x02, 0x7a, 0x30, 0x27, 0xe9,
	0x41, 0x6c, 0x0a, 0x02, 0x49, 0x0a, 0x89, 0x70, 0xb1, 0xa6, 0x82, 0x14, 0x83, 0x2d, 0xe1, 0x0c,
	0x82, 0x70, 0x8c, 0x66, 0x31, 0x72, 0x71, 0x3b, 0x27, 0xe6, 0x24, 0x07, 0xa7, 0x16, 0x95, 0x65,
	0x26, 0xa7, 0x0a, 0x59, 0x70, 0x31, 0x27, 0xa6, 0xa4, 0x08, 0x61, 0x98, 0x21, 0x25, 0x88, 0x26,
	0x52, 0x5c, 0xa0, 0xc4, 0xf3, 0xeb, 0xb3, 0x04, 0xc2, 0x0d, 0x96, 0x5c, 0x2c, 0x89, 0x29, 0x29,
	0x46, 0x64, 0x68, 0x95, 0x12, 0x6b, 0xfa, 0x22, 0x21, 0x04, 0x0d, 0x3d, 0x67, 0x30, 0x05, 0x16,
	0x77, 0xe2, 0x8d, 0xe2, 0x06, 0xe9, 0x2c, 0x2e, 0x2b, 0x02, 0x69, 0x4e, 0x62, 0x03, 0x87, 0xa0,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x86, 0xc6, 0x8a, 0x8e, 0x01, 0x00, 0x00,
}
